### ISSUE TITLE
Status so far?

### ISSUE THREAD

**Issue by mengstr** [btb/DiskII#1]
Hi Bradley, 

I just got an Apple // again after 40 years and unfortunately it was without a drive and the disk controller card. (I've already got an Apple drive without the enclosure that I bought by mistake a while back.) So I was just about to make some prototype cards so I could make a clone of the Disk II card myself doing the same as you - using regular eproms which of I have a metric crapton of. But then I saw your card at Adrians Digital Basement on YT and realised that why should I design it myself when there's something already out there.

You mention in the readme that this is a WIP - so I wonder how WIPpy is it? Do you recon It at least kinda works even if some greenwiring would be necessary?

**Comment by btb** [comment]
It really should work, it's very close to an exact copy of Apple's card. I simply haven't tested it myself yet due to not yet having a floppy drive or a floppy emulator to plug into it (I'm planning to build an SDisk II) and all of my free time is very limited at the moment.

**Comment by mengstr** [comment]
Then I'll give it a go. The only real issue is that the '323 is hard - not to say impossible - to find from any of the usual resellers like Farnell/Element14, Mouser, Digikey or TME. But they're at least available on eBay...

**Comment by btb** [comment]
> Then I'll give it a go. The only real issue is that the '323 is hard - not to say impossible - to find from any of the usual resellers like Farnell/Element14, Mouser, Digikey or TME. But they're at least available on eBay...

My favorite seller for items like that is https://unicornelectronics.com

**Comment by mengstr** [comment]
They definitely have a lot of nice retro stuff there. But it will end up costing me a bundle in total to get the chips from there, $30 minimum order + overseas shipping, $8 import processing fee and then some local VAT on top of all this.

I found a EU-based (Bulgaria) seller on ebay and got a pack of 10 of the 323's for $6.  Of course I added some USSR variants of the 8080 CPU, and some other interesting 1970's ICs and a tub of 1000 core memory ferrite cores as well ;)  

Edit: For anyone else in EU that needs a 74LS323 you can get them here: https://www.ebay.com/str/orpheus2005

**Comment by mengstr** [comment]
I received my PCBs today and soldered up one. I didn't have any 2-row RA connector so a normal one had to suffice. I also jumpered everything related to power save modes and the EPROM banks.

So tomorrow I try find the contents of the eproms and burn them and give it a go in my Apple 2e...  You don't happen to have the eprom bins/hexes available do you?
 
![IMG_20220827_232927__01](https://user-images.githubusercontent.com/325326/187048900-438ea80a-216a-49a6-abcf-df7d66b0a464.jpg)

**Comment by btb** [comment]
The images are here: https://mirrors.apple2.org.za/Apple%20II%20Documentation%20Project/Interface%20Cards/Disk%20Drive%20Controllers/Apple%20Disk%20II%20Interface%20Card/ROM%20Images/

You can map them into your EPROMs at whatever addresses you like, just set the a8, a9, a10 jumpers accordingly.

**Comment by veremenko-y** [comment]
I'm kinda curious about the status of this as well :)

**Comment by btb** [comment]
I finally got a real disk drive to test with, and this design does indeed have a fatal flaw. I'll put up some instructions for fixing it.

**Comment by btb** [comment]
I've described the problem and how to fix it here:
https://github.com/btb/DiskII/wiki/Revision-0-errata
