### ISSUE TITLE
R5 value

### ISSUE THREAD

**Issue by soboth** [btb/DiskII#3]
Looking at original schematics for Disk II interface, R5 seems to be 47KΩ not 49KΩ as per your design. Moreover 49K is practically impossible to find in the contrary to 47K.

**Comment by btb** [comment]
Indeed it is, I think that has to have been a typo. 47k is what I used in my builds.

**Comment by soboth** [comment]
Cool, thanks! That was my assumption as the rest of resistors have value as per original design. Although it's a minor issue to me, you might think of correcting the silkscreen and BOM.

**Comment by btb** [comment]
yep, it'll be fixed in next revision. thanks!
