### ISSUE TITLE
Error in the errata :)

### ISSUE THREAD

**Issue by mengstr** [btb/DiskII#4]
I finally started to apply the bugfix you described in the errata. But it seems like the new connections on the lower row of the EPROM are shifted one step to the left. What is designated as D2 is really the GND pin.

<img width="489" alt="DISKII" src="https://user-images.githubusercontent.com/325326/234361952-bf3f0cd5-94fa-4dee-aa7d-b5748b1005ff.png">

**Comment by btb** [comment]
😭

**Comment by btb** [comment]
fixed now
